[OWING]
url = 

[AVG]
url = 

[GIRO]
YA

[OWCOLKEY]
Nomor Invoice

[GIROKEY]


[GIRORET]


[AVGCOLPEL]
NO. PELANGGAN

[AVGARP]
AVG UMUR PIUTANG

[AVGINV]
AVG NILAI FAKTUR

[CALCINV]
JUMLAH INVOICE

[PLAFON]
PLAFON

[AVGPAY]
AVG BAYAR

[AVGHISPAY]
AVG HISTORY BAYAR (HARI)

[AR]
url =

[ARSHEET]


[ARCOLPEL]
KODE PELANGGAN

[ARCOL]
Nominal Nota Belum Lunas
