[DEPO]
dir = # AR DEPO/MGL SH/Jalankan Automasi.py
dir 1 = # AR DEPO/SLO SH/Jalankan Automasi.py
dir 2 = # AR DEPO/YGY SH/Jalankan Automasi.py
dir 3 = AR DEPO/PTI SH/Jalankan Automasi.py
dir 4 = # AR DEPO/TGL SH/Jalankan Automasi.py
dir 5 = # AR DEPO/PWT SH/Jalankan Automasi.py
dir 6 = AR DEPO/MKS SH/Jalankan Automasi.py
dir 7 = AR DEPO/MKS ZN/Jalankan Automasi.py
dir 8 = AR DEPO/KDI ZN/Jalankan Automasi.py
dir 9 = AR DEPO/KDI SH/Jalankan Automasi.py
dir 10 = AR DEPO/PLU SH/Jalankan Automasi.py
dir 11 = AR DEPO/SMG SH/Jalankan Automasi.py